basePath: /
definitions:
  controller.ArticleRequest:
    properties:
      content:
        type: string
      title:
        type: string
    required:
    - content
    - title
    type: object
  controller.ResponseError:
    properties:
      message:
        type: string
    type: object
  controller.UserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  models.Address:
    properties:
      address_full:
        type: string
      address_title:
        type: string
      created_at:
        type: string
      created_by:
        type: string
      district_name:
        type: string
      id:
        type: integer
      primary:
        type: boolean
      subdistrict_name:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
      user_id:
        type: integer
      zip_code:
        type: string
    required:
    - address_full
    - address_title
    - user_id
    type: object
  models.BaseResponse:
    properties:
      code:
        type: string
      data: {}
      error:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
host: localhost:9090
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Goscription Example API
  version: "1.0"
paths:
  /address:
    get:
      consumes:
      - application/json
      description: get address
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BaseResponse'
      summary: Show a Address
      tags:
      - address
    post:
      consumes:
      - application/json
      description: insert address
      parameters:
      - description: address
        in: body
        name: address
        required: true
        schema:
          $ref: '#/definitions/models.Address'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BaseResponse'
      summary: Show a Address
      tags:
      - address
  /articles:
    delete:
      consumes:
      - application/json
      description: Create an Article
      parameters:
      - description: Article ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ResponseError'
      summary: Create an Article
      tags:
      - articles
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: num
        in: query
        name: num
        required: true
        type: string
      - description: cursor
        in: query
        name: cursor
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ResponseError'
      summary: Show a Article
      tags:
      - articles
    post:
      consumes:
      - application/json
      description: Create an Article
      parameters:
      - description: Article Body
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/controller.ArticleRequest'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ResponseError'
      summary: Create an Article
      tags:
      - articles
  /articles/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      operationId: get-string-by-int
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ResponseError'
      summary: Show a Article
      tags:
      - articles
    put:
      consumes:
      - application/json
      description: Update an Article
      parameters:
      - description: Article Body
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/controller.ArticleRequest'
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ResponseError'
      summary: Update an Article
      tags:
      - articles
  /health:
    get:
      consumes:
      - application/json
      description: get health
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BaseResponse'
      summary: Show a Health
      tags:
      - health
  /user:
    post:
      consumes:
      - application/json
      description: Create an User
      parameters:
      - description: User Body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.UserRequest'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ResponseError'
      summary: Create an User
      tags:
      - users
  /user/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ResponseError'
      summary: Show a User
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
  OAuth2AccessCode:
    authorizationUrl: https://example.com/oauth/authorize
    flow: accessCode
    scopes:
      admin: ' Grants read and write access to administrative information'
    tokenUrl: https://example.com/oauth/token
    type: oauth2
  OAuth2Implicit:
    authorizationUrl: https://example.com/oauth/authorize
    flow: implicit
    scopes:
      admin: ' Grants read and write access to administrative information'
      write: ' Grants write access'
    type: oauth2
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
